### ISSUE TITLE
Add transfer to agent demo

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/helpdesk-assistant#17]
Add a dummy "hand off to human" skill

**Comment by rgstephens** [comment]
A possible project to fork for this feature - [agent-human-handoff-nodejs](https://github.com/dialogflow/agent-human-handoff-nodejs)

**Comment by melindaloubser1** [comment]
https://github.com/RasaHQ/customers/issues/185

**Comment by Mohmmadhd** [comment]
> [RasaHQ/customers#185](https://github.com/RasaHQ/customers/issues/185)

it returns 404

**Comment by melindaloubser1** [comment]
@Mohmmadhd since that is a private repo, you won't be able to access the link. However you can check out the work being done on this on the `handoff` branch; the majority of the implementation is via the front end; work on a chatroom version is happening here: https://github.com/RasaHQ/chatroom/tree/handoff. You'll see the PR is still open, but feel free to try it out in the meantime.
